### ISSUE TITLE
pooled AUC forest plot

### ISSUE THREAD

**Issue by codeenthusiast** [cjvanlissa/metaforest#8]
I am working on a meta-analysis on a particular diagnostic test for renal cell cancer. Each study reports the sample size, respective AUC, and the confidence intervals. Is it possible to do a pooled AUC forest plot of all the studies I have selected?
Many thanks!

**Comment by cjvanlissa** [comment]
Dear poster, yes it's possible - but this is not within the scope of the metaforest package, and GitHub issues in general are for bug reports and feature requests!
